### ISSUE TITLE
Review Suggestions 

### ISSUE THREAD

**Issue by arnima-agg** [gkomsai/cumbersome-circle-9157#73]
- Read me file is good with proper explanations and required docs
- Event and variable name is correct.
- Project is deployed ad working fine
- Code quality is also average, certain icons and page are not fully responsive. Add proper responsiveness to the website.
- Try to add backend as well to this project
- Report and team page is unnessary, either add some functionality to them or remove them
- Projects and clients are not getting created, whole calendar is hardcoded. This is the core functionality of the project atleast this should work properly.
- Remove unnecessary comments and empty files. Add meaning comments .
- Signin page is not working without signup. Improve that
- Google signup is redirecting to actual website signin page.
- In the footer, add website links to facebook, instagram icons( no need to create a new page on facebook, just add facebook url simply so that when user click it will redirect them to facebook or instagram).

**Comment by gkomsai** [comment]
Thank you very much ma'am for reviewing my code and giving suggestions. Due to time constraints, I haven't added those functionalities in the construct week, but I will surely work on your suggestions and improve my website functionalities.

Thank You!
